# ClusterIssuer for Let's Encrypt production certificates.
# This will temporarily fail until cert-manager CRDs are installed;
# ArgoCD's selfHeal will reconcile it once cert-manager is ready.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: br.kramjit@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
