apiVersion: v1
kind: Namespace
metadata:
  name: weather
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: weather
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: weather-service-mtls
  namespace: weather
spec:
  host: weather-service.weather.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
