fullnameOverride: home-kube-prometheus

grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.karamjitbrar.com
    path: /
    pathType: Prefix
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.karamjitbrar.com
  grafana.ini:
    server:
      root_url: https://grafana.karamjitbrar.com/
    security:
      allow_embedding: true
    auth.anonymous:
      enabled: true
      org_role: Viewer