fullnameOverride: home-kube-prometheus

common:
  nodeSelector:
    node-role.kubernetes.io/worker: "true"

prometheusOperator:
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: workload
                operator: In
                values: [platform]

prometheus:
  prometheusSpec:
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: workload
                  operator: In
                  values: [platform]

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: workload
                  operator: In
                  values: [platform]

grafana:
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: workload
                operator: In
                values: [platform]
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.karamjitbrar.com
    path: /
    pathType: Prefix
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.karamjitbrar.com
  grafana.ini:
    server:
      root_url: https://grafana.karamjitbrar.com/
    security:
      allow_embedding: true
    auth.anonymous:
      enabled: true
      org_role: Viewer

kube-state-metrics:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: workload
                operator: In
                values: [platform]