apiVersion: v1
kind: Service
metadata:
  name: n8n-db
  namespace: db
spec:
  selector:
    app: n8n-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n-db
  namespace: db
  labels:
    app: n8n-db
spec:
  serviceName: n8n-db
  replicas: 1
  selector:
    matchLabels:
      app: n8n-db
  template:
    metadata:
      labels:
        app: n8n-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: n8n
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-db-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-db-secrets
                  key: password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 512Mi
