apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-secrets
  namespace: db
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: n8n-db-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: n8n-db-username
    - secretKey: password
      remoteRef:
        key: n8n-db-password
