apiVersion: v1
kind: Namespace
metadata:
  name: hello
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: hello
spec:
  mtls:
    mode: PERMISSIVE
